signs:
  телец: taurus
  овен: aries
  близнецы: gemini
  рак: cancer
  лев: leo
  весы: libra
  стрелец: sagittarius
  козерог: capricorn
  водолей: aquarius
  рыбы: pisces
  дева: virgo
  скорпион: scorpio

public_pages:
  4ch:
    owner_id: -45745333
    album_id: 262436923
  this_is_not_nerves:
    owner_id: -176864224
    album_id: wall
  eblan_kingdom:
    owner_id: -29606875
    album_id: wall
  postironia:
    owner_id: -144918406
    album_id: wall

