signs:
  телец:
    named: taurus
    emoji: ♉
  овен:
    named: aries
    emoji: ♈
  близнецы:
    named: gemini
    emoji: ♊
  рак:
    named: cancer
    emoji: ♋
  лев:
    named: leo
    emoji: ♌
  весы:
    named: libra
    emoji: ♎
  стрелец:
    named: sagittarius
    emoji: ♐
  козерог:
    named: capricorn
    emoji: ♑
  водолей:
    named: aquarius
    emoji: ♒
  рыбы:
    named: pisces
    emoji: ♓
  дева:
    named: virgo
    emoji: ♍
  скорпион:
    named: scorpio
    emoji: ♏

public_pages:
  4ch:
    owner_id: -45745333
    album_id: 262436923
  this_is_not_nerves:
    owner_id: -176864224
    album_id: wall
  eblan_kingdom:
    owner_id: -29606875
    album_id: wall
  postironia:
    owner_id: -144918406
    album_id: wall
